config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users
  resources :promotions, only: %i[index show new create] do
    member do
    post 'generate_coupons'
    post 'approve'
    end
  end

  resources :coupons, only: [] do
    post 'inactivate', on: :member    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, inactive: 10 }
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :coupons
  has_one :promotion_approval
  belongs_to :user
  
  validates :name, :discount_rate, :code, :coupon_quantity, :expiration_date, presence: true
  validates :code, uniqueness: true

  def generate_coupons!
    Coupon.transaction do
      (1..coupon_quantity).each do |number|
        coupons.create!(code: "#{code}-#{'%04d' % number}")
      end
    end
  end

  def approve!(approval_user)
    PromotionApproval.create(promotion: self, user: approval_user)
  end

  def approved?
    promotion_approval
  end

  def approver
    promotion_approval.user
  end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def inactivate
    @coupon = Coupon.find(params[:id])
    @coupon.inactive!
    redirect_to @coupon.promotion
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @promotions = Promotion.all
    end

    def show
        @promotion = Promotion.find(params[:id])
    end

    def new
        @promotion = Promotion.new
    end

    def create
        promotion_params = params.require(:promotion).permit(:name, :description, :code,
                                                             :discount_rate, :coupon_quantity,
                                                             :expiration_date)
        @promotion = Promotion.new(promotion_params)
        @promotion.user = current_user
        
        if @promotion.save
            redirect_to @promotion
        else
            render 'new'
        end
    end

    def generate_coupons
        @promotion = Promotion.find(params[:id])
        @promotion.generate_coupons!
        redirect_to @promotion, notice: t('.success')
    end

    def approve
        promotion = Promotion.find(params[:id])
        promotion.approve!(current_user)
        redirect_to promotion
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3> Boas vindas ao sistema de gestão de promoções</h3>

<%= I18n.translate("hello") %>

<%= link_to 'Promoções', promotions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/promotions/index.html.erb
<% if @promotions.empty? %>
    <div class="warning">Nenhuma promoção cadastrada</div>
<% end %>

<% @promotions.each do |promotion| %>
    <div>
        <dl>
            <dt>Nome</dt>
            <dd><%= link_to promotion.name, promotion_path(promotion) %></dd>
            <dt>Descrição</dt>
            <dd><%= promotion.description %></dd>
            <dt>Porcentagem de desconto</dt>
            <dd><%= number_to_percentage(promotion.discount_rate, precision: 2, separator: ',') %></dd>
            <hr>
        </dl>
    </div>
<% end %>

<%= link_to 'Registrar uma promoção', new_promotion_path %>
<%= link_to 'Voltar', root_path %>

app/views/promotions/new.html.erb
<h1>Nova promoção</h1>
<% if @promotion.errors.any? %>
    <div class="alert">
        <p>Não foi possível criar a promoção</p>
        <p>Confira os erros abaixo:</p>
        <ul>
        <% @promotion.errors.full_messages.each do |m| %>
            <li><%= m %></li>
        <% end %>
        </ul>
    </div>
<% end %>
<%= form_with model: @promotion do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div>
        <%= f.label :code %>
        <%= f.text_field :code %>
    </div>
    <div>
        <%= f.label :discount_rate %>
        <%= f.text_field :discount_rate %>
    </div>
    <div>
        <%= f.label :coupon_quantity %>
        <%= f.text_field :coupon_quantity %>
    </div>
    <div>
        <%= f.label :expiration_date %>
        <%= f.text_field :expiration_date %>
    </div>
    <%= f.submit 'Criar promoção' %>

<% end %>

app/views/promotions/show.html.erb
<%= link_to 'Voltar', promotions_path %>

<h1><%= @promotion.name %></h1>
<span>Cadastrada por: <%= @promotion.user.email %>

<dl>
    <dt><%= Promotion.human_attribute_name(:description) %></dt>
    <dd><%= @promotion.description %></dd>
    <dt>Porcentagem de desconto</dt>
    <dd><%= number_to_percentage(@promotion.discount_rate, precision: 2, separator: ',') %></dd>
    <dt>Código da Promoção</dt>
    <dd><%= @promotion.code %>
    <dt>Data de Expiração</dt>
    <dd><%= I18n.localize(@promotion.expiration_date) %>
    <dt>Quantidade de Cupons</dt>
    <dd><%= @promotion.coupon_quantity %>

    <% if @promotion.approved? %>
        <dt>Status: </dt> <dd>Aprovada</dd>
    <% end %>
</dl>



<% unless current_user == @promotion.user %>
    <%= link_to 'Aprovar Promoção', approve_promotion_path, method: :post %>
<% end %>
<%= link_to 'Gerar cupons', generate_coupons_promotion_path(@promotion), method: :post %>


<% @promotion.coupons.each do |coupon| %>
    <div id="coupon-<%= coupon.id %>">
        <span> <%= coupon.code %> (<%= t(".#{coupon.status}") %>) </span>
        <% if coupon.active? %>
        <%= link_to 'Inativar', inactivate_coupon_path(coupon), method: :post %>  
    <% end %>
    </div>
<% end %>